version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env # Use the environment file for the backend
    ports:
      - "8000:8000"
    # Remove the ports directive for fastapi-backend to not expose it to the host
    networks:
      - app-network

  svelte-frontend:
    build:
      context: ./my-budget-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose Svelte frontend directly on port 80
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
