version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8083:8080" # Jenkins web interface
      - "50000:50000" # Jenkins agent port
    volumes:
      - jenkins_volume:/var/jenkins_home
    restart: always
    networks:
      - jenkins

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000" # SonarQube web interface
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonarpassword
    volumes:
      - sonarqube_volume:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - sonarqube_db
    restart: always
    networks:
      - jenkins

  sonarqube_db:
    image: postgres:12
    container_name: sonarqube_db
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonarpassword
    volumes:
      - sonarqube_db_volume:/var/lib/postgresql/data
    restart: always
    networks:
      - jenkins

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "9001:8081" # Nexus web interface
    volumes:
      - nexus_data:/nexus-data
    restart: always
    networks:
      - jenkins

  trivy:
    image: aquasec/trivy
    container_name: trivy
    command: server --listen 0.0.0.0:4954
    ports:
      - "4954:4954" # Trivy server port
    volumes:
      - trivy_data:/root/.cache/
    restart: always
    networks:
      - jenkins

volumes:
  jenkins_volume:
    driver: local
  sonarqube_volume:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_logs:
    driver: local
  sonarqube_db_volume:
    driver: local
  nexus_data:
    driver: local
  trivy_data:
    driver: local

networks:
  jenkins:
    driver: bridge
