version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8083:8080" # Jenkins web interface
      - "50000:50000" # Jenkins agent port
    volumes:
      - jenkins_volume:/var/jenkins_home
    restart: always
    networks:
      - jenkins

volumes:
  jenkins_volume:
    driver: local

networks:
  jenkins:
    driver: bridge
